baseURL = 'https://maxmachac.github.io/website/'
languageCode = 'en-us'
title = 'maxblog'
enableRobotsTXT = true

[caches.images]
    dir = ':cacheDir/images'

[outputs]
home = ["HTML", "RSS"]

[params]
mainSections = ["lessons", "snippets"]

[params.seoTitles]
  [params.seoTitles.contributors]
    suffix = " - Contributors | Fireship.io"
  [params.seoTitles.courses]
    prefix = "Learn "
    suffix = " Online Course | Fireship.io"
  [params.seoTitles.lessons]
    prefix = "Tutorial: "
    suffix = " | Fireship.io"
  [params.seoTitles.tags]
    suffix = " - Tags | Fireship.io"

[markup.goldmark.renderer]
unsafe= true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'monokai'
    tabWidth = 4

[security]
  allowContent = ["text/html"]
  enableInlineShortcodes = false

  [security.exec]
    allow = ['^(dart-)?sass$', '^go$', '^git$', '^node$', '^postcss$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|SYSTEMDRIVE|PROGRAMDATA)$']

  [security.funcs]
    getenv = ['^HUGO_', '^CI$']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['(?i)^https?://[a-z0-9]', '! ^https?://\d+\.', '! (?i)localhost', '! (?i)^https?://[^/?#]*@']

  [security.node]
    [security.node.permissions]
      allowAddons = ['tailwindcss']
      allowChildProcess = ['tailwindcss']
      allowRead = ['.']
      allowWorker = ['tailwindcss']
      allowWrite = []
      disable = false