name: Deploy

on:
  push:
    branches:
      - master

env:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.101.0'
          extended: true
      - run: bun install
      - run: bun run build
      - run: bun run deploy
